name: Python Package CI/CD Workflow

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: weastur/poetry:latest-python-3.11
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: poetry install
      - name: quality
        run: make quality
      - name: Run tests
        run: make test
