name: Python Package CI/CD Workflow

on:
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: weastur/poetry:latest-python-3.11
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: poetry install && apt-get update && apt-get install -y git &&  git config --global --add safe.directory ../
      - name: quality
        run: make quality
      - name: Run tests
        run: make test
