name: Python Package CI/CD Workflow

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    container:
      image: weastur/poetry:latest-python-3.11
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: poetry install && apt-get update && apt-get install -y git &&  git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: quality
        run: make quality
      - name: Run tests
        run: make test
      - name: Increment package version and commit
        run: |
          poetry version patch
          git config --global user.email "octavio.delser@gmail.com"
          git config --global user.name "occy88"
          git commit -am "Increment package version [skip ci]"
          git push
      - name: publish
        env:
          TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish --build --username __token__ --password ${{secrets.PYPI_API_TOKEN}}
