name: Python Package CI/CD Workflow

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    container: 
      image: paketobuildpacks/poetry:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: poetry install
    - name: quality
      run: make quality
    - name: Run tests
      run: make test
    - name: Run build
      run: poetry build
    - name: publish
      run: poetry publish